language: cpp
os: linux
dist: bionic
compiler:
  - clang
  - gcc
env:
  - CXXFLAGS="-Wall -Werror"
script:
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXE_LINKER_FLAGS=${LINKER_FLAGS} .
  - cmake --build . -- VERBOSE=1
