CMAKE_MINIMUM_REQUIRED(VERSION 3.14)
PROJECT(laskin C CXX)

IF(EMSCRIPTEN)
  SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)
  SET(LASKIN_ENABLE_CLI_DEFAULT OFF)
  SET(LASKIN_ENABLE_GUI_DEFAULT OFF)
  SET(LASKIN_ENABLE_2CPP_DEFAULT OFF)
  SET(LASKIN_ENABLE_WEB_DEFAULT ON)
ELSE()
  SET(LASKIN_ENABLE_CLI_DEFAULT ON)
  SET(LASKIN_ENABLE_GUI_DEFAULT OFF)
  SET(LASKIN_ENABLE_2CPP_DEFAULT OFF)
  SET(LASKIN_ENABLE_WEB_DEFAULT OFF)
ENDIF()

OPTION(
  LASKIN_ENABLE_CLI
  "Whether CLI interpreter should be built or not."
  ${LASKIN_ENABLE_CLI_DEFAULT}
)
OPTION(
  LASKIN_ENABLE_GUI
  "Whether GUI interpreter should be built or not."
  ${LASKIN_ENABLE_GUI_DEFAULT}
)
OPTION(
  LASKIN_ENABLE_2CPP
  "Whether C++ transpiler should be built or not."
  ${LASKIN_ENABLE_2CPP_DEFAULT}
)
OPTION(
  LASKIN_ENABLE_WEB
  "Whether WebAssembly/JavaScript bindings should be built or not."
  ${LASKIN_ENABLE_WEB_DEFAULT}
)

ADD_SUBDIRECTORY(laskin)
IF(LASKIN_ENABLE_CLI)
  ADD_SUBDIRECTORY(cli)
ENDIF()
IF(LASKIN_ENABLE_GUI)
  ADD_SUBDIRECTORY(gui)
ENDIF()
IF(LASKIN_ENABLE_2CPP)
  ADD_SUBDIRECTORY(2cpp)
ENDIF()
IF(LASKIN_ENABLE_WEB)
  ADD_SUBDIRECTORY(web)
ENDIF()
