name: build

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: install MPFR
        run: sudo apt install -y libmpfr6 libmpfr-dev
      - name: configure
        run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Wall -Werror" ..
      - name: build
        run: cmake --build build
